import type { ProductCategory } from "../types/order";

interface CategoryRule {
  category: ProductCategory;
  keywords: readonly string[];
}

// Reihenfolge = Priorität. Spezifischere Kategorien zuerst.
const RULES: readonly CategoryRule[] = [
  {
    category: "computer",
    keywords: [
      "laptop",
      "notebook",
      "macbook",
      "chromebook",
      "keyboard",
      "tastatur",
      "monitor",
      "bildschirm",
      "mouse",
      "maus",
      "mousepad",
      "trackpad",
      "ssd",
      "festplatte",
      "arbeitsspeicher",
      "grafikkarte",
      " ram ",
      " cpu",
      " gpu",
      "webcam",
      "docking station",
      "dockingstation",
    ],
  },
  {
    category: "spielzeug",
    keywords: [
      "lego",
      "playmobil",
      "spielzeug",
      "puzzle",
      "brettspiel",
      "board game",
      "barbie",
      "action figure",
      "plüschtier",
      "plush toy",
      " toy",
    ],
  },
  {
    category: "buecher",
    keywords: [
      "taschenbuch",
      "hardcover",
      "paperback",
      "buch",
      "book",
      "roman",
      "novel",
      "kindle edition",
      "hörbuch",
      "audiobook",
      "kochbuch",
    ],
  },
  {
    category: "garten",
    keywords: [
      "garten",
      "garden",
      "blumentopf",
      "flower pot",
      "pflanze",
      "plant",
      "blumenerde",
      "blumensamen",
      "rasenmäher",
      "lawn mower",
      "gartenschlauch",
      "garden hose",
      "gartenschere",
      "pruning shears",
    ],
  },
  {
    category: "kueche",
    keywords: [
      "pfanne",
      "bratpfanne",
      " pan ",
      "topf",
      " pot ",
      "messer",
      "knife",
      "kitchen",
      "backform",
      "bakeware",
      "vorratsdose",
      "gewürz",
      "spice",
      "kochlöffel",
      "schneidebrett",
      "cutting board",
      "dampfgarer",
      "mixer ",
    ],
  },
  {
    category: "beauty",
    keywords: [
      "shampoo",
      "conditioner",
      "creme",
      "cream",
      "lotion",
      "duschgel",
      "shower gel",
      "seife",
      " soap",
      "zahnbürste",
      "toothbrush",
      "zahnpasta",
      "toothpaste",
      "rasierer",
      "razor",
      "deodorant",
      "parfüm",
      "perfume",
      "nagellack",
      "nail polish",
    ],
  },
  {
    category: "kleidung",
    keywords: [
      "t-shirt",
      "shirt",
      "hose",
      "jeans",
      "pants",
      "trouser",
      "jacke",
      "jacket",
      "mantel",
      " coat",
      "socken",
      "socks",
      "schuhe",
      "shoes",
      "sneaker",
      "pullover",
      "sweater",
      "hoodie",
      "kleid",
      " dress",
      "rock ",
      "skirt",
      "wolle",
    ],
  },
  {
    category: "buero",
    keywords: [
      "ordner",
      " folder",
      "stift",
      " pen ",
      "kugelschreiber",
      "papier",
      "paper",
      "druckerpatrone",
      "toner",
      "patrone",
      "cartridge",
      "drucker",
      "printer",
      "tacker",
      "stapler",
      "locher",
      "hole punch",
      "briefumschlag",
      "envelope",
    ],
  },
  {
    category: "lebensmittel",
    keywords: [
      "kaffee",
      "coffee",
      " tee ",
      "tea bags",
      "espresso",
      "müsli",
      "cereal",
      "protein riegel",
      "protein bar",
      "snack",
      "riegel",
      "schokolade",
      "chocolate",
      "bonbon",
      "bio ",
      "organic ",
    ],
  },
  {
    category: "elektronik",
    keywords: [
      "kabel",
      "cable",
      "usb",
      "hdmi",
      "displayport",
      "ladegerät",
      "charger",
      "ladekabel",
      "kopfhörer",
      "headphone",
      "earbud",
      "ohrstöpsel",
      "bluetooth",
      "adapter",
      "powerbank",
      "lautsprecher",
      "speaker",
      "fernbedienung",
      "remote",
      "akku",
      "battery pack",
      " hub",
      "dongle",
      "router",
      "switch",
    ],
  },
  {
    category: "haushalt",
    keywords: [
      "spülmittel",
      "müllbeutel",
      "trash bag",
      "glühbirne",
      "bulb",
      "light bulb",
      "batterien",
      "aa battery",
      "aaa battery",
      "reiniger",
      "cleaner",
      "waschmittel",
      "detergent",
      "toilettenpapier",
      "toilet paper",
      "küchenrolle",
      "paper towel",
      "staubsauger",
      "vacuum",
    ],
  },
];

export function inferCategory(productName: string): ProductCategory {
  if (!productName) {
    return "sonstiges";
  }
  // Padding mit Leerzeichen, damit Keywords wie " ram " oder " toy" auch am Wortanfang/-ende matchen.
  const padded = ` ${productName.toLowerCase()} `;
  for (const rule of RULES) {
    for (const kw of rule.keywords) {
      if (padded.includes(kw)) {
        return rule.category;
      }
    }
  }
  return "sonstiges";
}
